user_pref("font.name.monospace.x-western", "Maple Mono NF CN");
user_pref("font.name.monospace.zh-CN", "Maple Mono NF CN");
user_pref("font.name.sans-serif.x-western", "Maple Mono NF CN");
user_pref("font.name.sans-serif.zh-CN", "Maple Mono NF CN");
user_pref("font.size.monospace.x-western", 14);
user_pref("font.size.monospace.zh-CN", 14);
user_pref("font.size.variable.x-western", 14);
user_pref("font.size.variable.zh-CN", 14);
user_pref("mail.chat.enabled", false);
user_pref("mail.server.server11.autosync_max_age_days", 90);
user_pref("mail.server.server12.autosync_max_age_days", 90);
user_pref("mail.server.server8.autosync_max_age_days", 90);
user_pref("mail.server.server9.autosync_max_age_days", 90);
user_pref("mail.uidensity", 0);
user_pref("mailnews.start_page.enabled", false);
user_pref("network.proxy.socks_port", 1080);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.type", 1);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
